name: "IronLayer Plan"
description: "Run ironlayer plan on a PR, post a formatted comment with data impact analysis, and upload the plan artifact."
branding:
  icon: "database"
  color: "blue"

inputs:
  repo-path:
    description: "Path to the repository root containing SQL models."
    required: false
    default: "."
  python-version:
    description: "Python version to install."
    required: false
    default: "3.11"
  ironlayer-version:
    description: "IronLayer package version (e.g. '0.1.0'). Defaults to latest."
    required: false
    default: "latest"
  api-url:
    description: "IronLayer API URL for AI-powered analysis (optional)."
    required: false
    default: ""
  api-token:
    description: "IronLayer API token (optional). Store as a repository secret."
    required: false
    default: ""
  comment:
    description: "Post or update a PR comment with the plan summary."
    required: false
    default: "true"
  upload-artifact:
    description: "Upload plan.json as a workflow artifact."
    required: false
    default: "true"

outputs:
  plan-id:
    description: "The deterministic plan ID (SHA-256)."
    value: ${{ steps.plan.outputs.plan_id }}
  total-steps:
    description: "Number of execution steps in the plan."
    value: ${{ steps.plan.outputs.total_steps }}
  estimated-cost:
    description: "Estimated compute cost in USD."
    value: ${{ steps.plan.outputs.estimated_cost }}
  models-changed:
    description: "Comma-separated list of changed model names."
    value: ${{ steps.plan.outputs.models_changed }}
  plan-status:
    description: "Plan generation status: success, empty, or failed."
    value: ${{ steps.plan.outputs.plan_status }}
  plan-json-path:
    description: "Path to the generated plan.json file."
    value: ${{ steps.plan.outputs.plan_json_path }}
  columns-added:
    description: "Total number of columns added across all models."
    value: ${{ steps.plan.outputs.columns_added }}
  columns-removed:
    description: "Total number of columns removed across all models."
    value: ${{ steps.plan.outputs.columns_removed }}
  columns-modified:
    description: "Total number of columns modified across all models."
    value: ${{ steps.plan.outputs.columns_modified }}
  risk-level:
    description: "Risk level: low risk, review, or high risk."
    value: ${{ steps.plan.outputs.risk_level }}

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install IronLayer
      shell: bash
      run: |
        if [ "${{ inputs.ironlayer-version }}" = "latest" ]; then
          pip install --quiet ironlayer
        else
          pip install --quiet "ironlayer==${{ inputs.ironlayer-version }}"
        fi

    - name: Generate execution plan
      id: plan
      shell: bash
      env:
        IRONLAYER_API_URL: ${{ inputs.api-url }}
        IRONLAYER_API_TOKEN: ${{ inputs.api-token }}
      run: |
        set +e
        PLAN_JSON_PATH="${{ runner.temp }}/ironlayer-plan.json"

        STDERR_FILE=$(mktemp)
        ironlayer plan "${{ inputs.repo-path }}" \
          "${{ github.event.pull_request.base.sha }}" \
          "${{ github.event.pull_request.head.sha }}" \
          --out "$PLAN_JSON_PATH" \
          --json 2>"$STDERR_FILE"
        EXIT_CODE=$?
        set -e

        echo "plan_json_path=$PLAN_JSON_PATH" >> "$GITHUB_OUTPUT"
        echo "exit_code=$EXIT_CODE" >> "$GITHUB_OUTPUT"

        if [ $EXIT_CODE -ne 0 ]; then
          echo "plan_status=failed" >> "$GITHUB_OUTPUT"
          STDERR_CONTENT=$(cat "$STDERR_FILE")
          # Escape for multiline GITHUB_OUTPUT
          {
            echo "error_message<<IRONLAYER_EOF"
            echo "$STDERR_CONTENT"
            echo "IRONLAYER_EOF"
          } >> "$GITHUB_OUTPUT"
          echo "::error::IronLayer plan failed with exit code $EXIT_CODE"
          cat "$STDERR_FILE"
        elif [ -f "$PLAN_JSON_PATH" ]; then
          python3 -c "
        import json, os

        plan = json.load(open('$PLAN_JSON_PATH'))
        summary = plan.get('summary', {})
        steps = plan.get('steps', [])
        gh_out = os.environ['GITHUB_OUTPUT']

        total = summary.get('total_steps', len(steps))
        cost = summary.get('estimated_cost_usd', 0)
        models = summary.get('models_changed', [])
        plan_id = plan.get('plan_id', 'unknown')

        # Aggregate column-level diff counts.
        cols_added = cols_removed = cols_modified = 0
        has_removed = False
        for step in steps:
            dd = step.get('diff_detail')
            if dd:
                cols_added += len(dd.get('columns_added', []))
                cols_removed += len(dd.get('columns_removed', []))
                cols_modified += len(dd.get('columns_modified', []))
                if dd.get('columns_removed'):
                    has_removed = True

        # Compute risk level.
        breaking = summary.get('breaking_contract_violations', 0)
        if breaking > 0:
            risk = 'high risk'
        elif has_removed:
            risk = 'review'
        else:
            risk = 'low risk'

        with open(gh_out, 'a') as f:
            f.write(f'plan_id={plan_id}\n')
            f.write(f'total_steps={total}\n')
            f.write(f'estimated_cost={cost:.2f}\n')
            f.write(f'models_changed={chr(44).join(models)}\n')
            f.write(f'columns_added={cols_added}\n')
            f.write(f'columns_removed={cols_removed}\n')
            f.write(f'columns_modified={cols_modified}\n')
            f.write(f'risk_level={risk}\n')

        if total == 0:
            with open(gh_out, 'a') as f:
                f.write('plan_status=empty\n')
        else:
            with open(gh_out, 'a') as f:
                f.write('plan_status=success\n')
        "
        else
          echo "plan_status=empty" >> "$GITHUB_OUTPUT"
          echo "total_steps=0" >> "$GITHUB_OUTPUT"
          echo "columns_added=0" >> "$GITHUB_OUTPUT"
          echo "columns_removed=0" >> "$GITHUB_OUTPUT"
          echo "columns_modified=0" >> "$GITHUB_OUTPUT"
          echo "risk_level=low risk" >> "$GITHUB_OUTPUT"
        fi

        rm -f "$STDERR_FILE"

    - name: Fetch AI advisory
      if: inputs.api-url != '' && inputs.api-token != '' && steps.plan.outputs.plan_status == 'success'
      id: advisory
      shell: bash
      run: |
        ADVISORY_PATH="${{ runner.temp }}/ironlayer-advisory.json"
        python3 "${{ github.action_path }}/fetch_advisory.py" \
          --api-url "${{ inputs.api-url }}" \
          --api-token "${{ inputs.api-token }}" \
          --plan-json "${{ steps.plan.outputs.plan_json_path }}" \
          --output "$ADVISORY_PATH" || true
        echo "advisory_path=$ADVISORY_PATH" >> "$GITHUB_OUTPUT"

    - name: Build PR comment
      if: inputs.comment == 'true' && github.event_name == 'pull_request'
      id: comment
      shell: bash
      run: |
        COMMENT_FILE="${{ runner.temp }}/ironlayer-comment.md"
        PLAN_JSON_PATH="${{ steps.plan.outputs.plan_json_path }}"
        PLAN_STATUS="${{ steps.plan.outputs.plan_status }}"
        ERROR_MSG="${{ steps.plan.outputs.error_message }}"
        BASE_SHA="${{ github.event.pull_request.base.sha }}"
        HEAD_SHA="${{ github.event.pull_request.head.sha }}"
        ADVISORY_PATH="${{ steps.advisory.outputs.advisory_path }}"

        # Build advisory flag — only pass if the file exists and is non-empty.
        ADVISORY_FLAG=""
        if [ -n "$ADVISORY_PATH" ] && [ -f "$ADVISORY_PATH" ] && [ -s "$ADVISORY_PATH" ]; then
          ADVISORY_FLAG="--advisory-json $ADVISORY_PATH"
        fi

        python3 "${{ github.action_path }}/format_comment.py" \
          --status "$PLAN_STATUS" \
          --plan-json "$PLAN_JSON_PATH" \
          --base-sha "$BASE_SHA" \
          --head-sha "$HEAD_SHA" \
          --error "$ERROR_MSG" \
          $ADVISORY_FLAG \
          --output "$COMMENT_FILE"

        echo "comment_file=$COMMENT_FILE" >> "$GITHUB_OUTPUT"

    - name: Post or update PR comment
      if: inputs.comment == 'true' && github.event_name == 'pull_request'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        COMMENT_FILE="${{ steps.comment.outputs.comment_file }}"
        PR_NUMBER="${{ github.event.pull_request.number }}"
        REPO="${{ github.repository }}"
        MARKER="<!-- ironlayer-plan-comment -->"

        # Check if we already have an IronLayer comment on this PR
        EXISTING_COMMENT_ID=$(gh api \
          "repos/$REPO/issues/$PR_NUMBER/comments" \
          --paginate \
          --jq ".[] | select(.body | contains(\"$MARKER\")) | .id" \
          | head -1)

        # Prepend the marker to the comment body
        BODY="${MARKER}
        $(cat "$COMMENT_FILE")"

        if [ -n "$EXISTING_COMMENT_ID" ]; then
          # Update existing comment
          gh api \
            "repos/$REPO/issues/comments/$EXISTING_COMMENT_ID" \
            -X PATCH \
            --field body="$BODY" \
            --silent
          echo "Updated existing comment $EXISTING_COMMENT_ID"
        else
          # Create new comment
          gh api \
            "repos/$REPO/issues/$PR_NUMBER/comments" \
            -X POST \
            --field body="$BODY" \
            --silent
          echo "Created new comment"
        fi

    - name: Upload plan artifact
      if: inputs.upload-artifact == 'true' && steps.plan.outputs.plan_status == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: ironlayer-plan
        path: ${{ steps.plan.outputs.plan_json_path }}
        retention-days: 30
