name: "IronLayer Plan"
description: "Generate a deterministic execution plan from a git diff and post it as a PR comment."
branding:
  icon: "database"
  color: "blue"

inputs:
  repo-path:
    description: "Path to the repository root containing SQL models."
    required: false
    default: "."
  python-version:
    description: "Python version to install."
    required: false
    default: "3.11"
  ironlayer-version:
    description: "IronLayer package version to install (e.g. '0.1.0'). Use 'latest' for the newest release."
    required: false
    default: "latest"
  api-url:
    description: "IronLayer Cloud API URL for AI-powered cost estimates (optional)."
    required: false
    default: ""
  api-token:
    description: "IronLayer Cloud API token for AI-powered cost estimates (optional). Store as a repository secret."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install IronLayer
      shell: bash
      run: |
        if [ "${{ inputs.ironlayer-version }}" = "latest" ]; then
          pip install --quiet ironlayer
        else
          pip install --quiet "ironlayer==${{ inputs.ironlayer-version }}"
        fi

    - name: Configure cloud credentials
      if: inputs.api-token != ''
      shell: bash
      run: |
        mkdir -p ~/.ironlayer
        API_URL="${{ inputs.api-url }}"
        if [ -z "$API_URL" ]; then
          API_URL="https://api.ironlayer.app"
        fi
        cat > ~/.ironlayer/config.toml <<TOML
        [cloud]
        api_url = "$API_URL"
        api_token = "${{ inputs.api-token }}"
        TOML
        chmod 600 ~/.ironlayer/config.toml

    - name: Generate execution plan
      id: plan
      shell: bash
      env:
        IRONLAYER_API_URL: ${{ inputs.api-url }}
        IRONLAYER_API_TOKEN: ${{ inputs.api-token }}
      run: |
        set +e
        PLAN_OUTPUT=$(ironlayer --json plan "${{ inputs.repo-path }}" \
          "${{ github.event.pull_request.base.sha }}" \
          "${{ github.event.pull_request.head.sha }}" \
          --out plan.json 2>&1)
        EXIT_CODE=$?
        set -e

        # Write plan JSON output for downstream steps.
        echo "exit_code=$EXIT_CODE" >> "$GITHUB_OUTPUT"

        if [ $EXIT_CODE -ne 0 ]; then
          echo "plan_status=failed" >> "$GITHUB_OUTPUT"
          echo "plan_summary=Plan generation failed." >> "$GITHUB_OUTPUT"
        else
          echo "plan_status=success" >> "$GITHUB_OUTPUT"

          # Extract summary fields from plan JSON.
          if [ -f plan.json ]; then
            TOTAL_STEPS=$(python3 -c "import json; d=json.load(open('plan.json')); print(d.get('summary',{}).get('total_steps',0))")
            EST_COST=$(python3 -c "import json; d=json.load(open('plan.json')); print(f\"\${d.get('summary',{}).get('estimated_cost_usd',0):.2f}\")")
            MODELS=$(python3 -c "import json; d=json.load(open('plan.json')); print(', '.join(d.get('summary',{}).get('models_changed',[])))")
            echo "total_steps=$TOTAL_STEPS" >> "$GITHUB_OUTPUT"
            echo "estimated_cost=$EST_COST" >> "$GITHUB_OUTPUT"
            echo "models_changed=$MODELS" >> "$GITHUB_OUTPUT"
          fi
        fi

    - name: Build plan summary table
      id: comment
      shell: bash
      run: |
        if [ "${{ steps.plan.outputs.plan_status }}" = "failed" ]; then
          BODY="## IronLayer Plan

        :x: **Plan generation failed.**

        Check the workflow logs for details.

        ---
        *Generated by [IronLayer](https://ironlayer.app) via GitHub Actions*"
        else
          TOTAL="${{ steps.plan.outputs.total_steps }}"
          COST="${{ steps.plan.outputs.estimated_cost }}"
          MODELS="${{ steps.plan.outputs.models_changed }}"

          # Build a Markdown table with step details if plan.json exists.
          STEP_TABLE=""
          if [ -f plan.json ]; then
            STEP_TABLE=$(python3 -c "
        import json, sys
        try:
            plan = json.load(open('plan.json'))
            steps = plan.get('steps', [])
            if not steps:
                print('No steps in plan.')
                sys.exit(0)
            lines = ['| # | Model | Run Type | Estimated Cost |', '|---|---|---|---|']
            for i, s in enumerate(steps, 1):
                model = s.get('model', 'unknown')
                run_type = s.get('run_type', 'unknown')
                cost = f\"\${s.get('estimated_cost_usd', 0):.2f}\"
                lines.append(f'| {i} | \`{model}\` | {run_type} | {cost} |')
            print('\n'.join(lines))
        except Exception as e:
            print(f'Error building table: {e}', file=sys.stderr)
            print('Could not parse plan details.')
        ")
          fi

          BODY="## IronLayer Plan

        | Metric | Value |
        |---|---|
        | **Total Steps** | ${TOTAL} |
        | **Estimated Cost** | ${COST} |
        | **Models Changed** | ${MODELS} |

        <details>
        <summary>Step Details</summary>

        ${STEP_TABLE}

        </details>

        ---
        *Generated by [IronLayer](https://ironlayer.app) via GitHub Actions*"
        fi

        # Write to a file for the comment step.
        echo "$BODY" > /tmp/ironlayer-comment.md

    - name: Post PR comment
      if: github.event_name == 'pull_request'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh pr comment "${{ github.event.pull_request.number }}" \
          --repo "${{ github.repository }}" \
          --body-file /tmp/ironlayer-comment.md
